services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      target: Build
    ports:
      - 5000:5000
      - 9229:9229 # for debuging!
    volumes:
      - .:/build
      - /build/node_modules
    command: npm run serve
    environment:
      - PORT=5000
